version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=trello-clone.localhost/api,trello-clone.localhost/api/*
      - VIRTUAL_HOST_WEIGHT=1
    expose:
      - 3000
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - VIRTUAL_HOST=trello-clone.localhost
      - VIRTUAL_HOST_WEIGHT=0
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    expose:
      - 8080

  load-balancer:
    image: dockercloud/haproxy
    links:
      - backend
      - frontend
    networks:
      default:
        aliases:
          - trello-clone.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure
